### ISSUE TITLE
ReadByteSlice and FromByteSlice are unsound

### ISSUE THREAD

**Issue by 197g** [DoumanAsh/lazy-bytes-cast#1]
As exmplary code, let's look at the implementation of `FromByteSlice`:

https://github.com/DoumanAsh/lazy-bytes-cast/blob/master/src/slice.rs#L121-L139

Note how the method `from_slice_unchecked` relies on casting a `&[u8]` into a pointer to associated type `Self::Array` which comes from `array::FromByteArray`. This is not sound in general. Any other crate could implement `FromByteArray` and use an almost arbitrary associated type (note how all trait bounds are safe and could even be implemented with pure `unimplemented` shims, `Copy` doesn't really stop anything as well).

Consider for example:

```rust
#[derive(Clone, Copy, Debug)]
struct BadArray(&'static [u8]);

impl AsRef<[u8]> for BadArray {
    fn as_ref(&self) -> &[u8] { &[] }
}

impl AsMut<[u8]> for BadArray {
    fn as_mut(&mut self) -> &mut [u8] { &mut [] }
}

impl Borrow<[u8]> for BadArray {
    fn borrow(&self) -> &[u8] { &[] }
}

impl BorrowMut<[u8]> for BadArray {
    fn borrow_mut(&mut self) -> &mut [u8] { &mut [] }
}

impl lazy_bytes_cast::array::FromByteArray for BadArray {
    type Array = Self;
    fn from_byte_array(own: Self) -> Self { own }
}
```

The following code then leads to multiple different UBs in the implementation of `FromByteSlice::from_slice` as provided by the crate. Firstly, an unaligned `* const BadArray` might be dereference and read from in the process. Secondly, it effectively transmutes the slice into a instance of `BadArray` but with its pointer set to null, which is *invalid* for references.

```rust
    let bad = [0u8; core::mem::size_of::<BadArray>()];
    let nullref: BadArray = lazy_bytes_cast::FromByteSlice::from_slice(&bad[..]).unwrap();
```

We could do worse. Since nothing verifies that `size_of::<Self> == size_of::<Self::Array>` for implementors, we could also do out of bounds reads with slightly modified versions but I considered the above the more critical issue as it can not be fixed by adding some more dynamic chekcs but must be fixed by making the `FromByteArray` trait itself `unsafe` or every consumer.

**Comment by DoumanAsh** [comment]
Ok, probably can be solved by making `FromByteArray` unsafe

There is no way to make these 3pp trait implementations trustworthy precisely because they can violate contract. (another breaking change :()
Unless you imply that these traits are unsound even when `FromByteArray` is implemented correctly?

**Comment by HeroicKatora** [comment]
I didn't find any more unsoundess and `unsafe trait FromByteArray` should suffice for fixing this issue but didn't do a comprehensive review of other parts of the crate.

**Comment by DoumanAsh** [comment]
Ok, thank you
